name: CI

on:
  push:
    branches:
      - yangand

jobs:

  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run:  ./autogen.sh && ./configure
    - name: make
      run:  make
    - name: check
      run:  make check
    - name: install
      run:  make install
